#JPA configuration
spring:
  datasource:
    url: jdbc:h2:mem:shopping;db_close_on_exit=false
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
management:
  security:
    enabled: false